### ISSUE TITLE
Some apps "result in" two app icons

### ISSUE THREAD

**Issue by just-Nob** [quaap/LaunchTime#28]
In v. 0.3 as well as  v. 0.4 maybe also in oder versions?), there are two icons shown (https://play.google.com/store/apps/details?id=me.kuder.diskinfo).
The LG G3's stock launcher only displays one icon.

**Comment by just-Nob** [comment]
Had the same trouble with another app, with "Quoka".

**Comment by quaap** [comment]
I finally tested this (had computer problems and family issues) and see the double icons. The problem is that the installation is creating an additional homescreen shortcut.  I'll look into how I'm supposed to handle that situation (stock homescreen does not display the link).

In the meantime, you can delete the link.  To find out which is the link, long click and hold on one of them and see which drop zone appears then the bottom corner.  If it is yellow and says "Remove", that's the link.

**Comment by quaap** [comment]
This prevents it:
https://www.howtogeek.com/206088/how-to-avoid-automatically-adding-shortcuts-to-the-home-screen-for-installed-apps-in-android/

It seems like an option for the standard google homescreen which has the app-drawer setup.  My stock homescreen (LG / Verizon) is more of an IOS layout, so it must ignore the request to create the shortcut at installation time.

I'm not sure why other apps from the play store do not have the issue, though. 

I'll look into fixing it.

**Comment by just-Nob** [comment]
I'm going to have a look on your hints asap.
Thanks for your efforts.
