### ISSUE TITLE
Misbehaviour of category "Other"

### ISSUE THREAD

**Issue by mase76** [quaap/LaunchTime#33]
Hi!
I have a category named "Navigation". It is possible, that it was named "Other"
before, as I have this structure since the first version you released.
Since you implemented, that new apps go to "Other", I have created this
category again. But new apps always went to "Navigation". I renamed
"Navigation" to "Other" and created a new Category "Navigation". Now new
apps go to "Other", as they should. Is it possible, that LT does not completely
notice the renaming of the category?

Another thing, I have unchecked auto-categorize. I uninstalled an app and
reinstalled it again. Instead of being placed in "Other", it is placed in the category,
where it was before.

**Comment by quaap** [comment]
I think the first issue should probably be considered a documentation problem.  A few of the categories are special and you can't delete them: Search, Communication, Other, and Hidden, if memory serves.  I did allow renaming them so they'd feel less in the way if the user didn't like them as-is.  However, they still behave the same, on purpose (for example, so apps can have a default category) . I'll think over adding some sort of on-screen indication that renaming a special category is a cosmetic change only.

The second is a necessary bug: to avoid un-categorizing apps the user has categorized just because of an update or reinstall.  I felt most people would be surprised if their apps moved on reinstall.

Thanks for trying and reporting!

**Comment by just-Nob** [comment]
One small idea Rendering to the second:
Is there a chance to decide whether an app is (re-)installed or just updated?
If so, LaunchTime could display a requester with a hint that the reinstalled app was previously installed one time ago and was sorted in category <xy>, and a request of to sort it in that category again. A special case occurs, if the category was deleted inn between...
