### ISSUE TITLE
Bug: ForkHub doesn't appear 

### ISSUE THREAD

**Issue by EdenDorf** [quaap/LaunchTime#35]
I installed ForkHub from F-Droid and i get the toast that its sorted to Utilities. But there is no.

**Comment by quaap** [comment]
Do you also have the github app installed?  If so, that explains it.  I discovered a bug the other day where if two apps have the same activity name, only one will be shown. Both github and forkhub have the same name for the main activity. I was surprised no one had run into it. :)

This is fixed in the next version.

**Comment by EdenDorf** [comment]
Yep i looked into the apps to decide what i would like to prefer. Okay, so, nothing new here. :D 
Nice that you are that aktive :+1:
