### ISSUE TITLE
Two icon launchers in Trebuchet

### ISSUE THREAD

**Issue by tetris4** [quaap/LaunchTime#6]
It appears that there are two icons for LaunchTime in Trebuchet. I noticed that one has the little gear on it, but still they seem to be doing the same thing when pressed, which is launching LaunchTime. 

Am guessing this is not the expected behaviour so I thought to report it.

**Comment by quaap** [comment]
The one with the gear is supposed to open the settings/preferences.  It works in the native launcher and in LaunchTime.  I suspect Trebuchet is using the packagename only instead of the packagename and activityname together.   Tuxpaint also has two launchers, and I bet it'd work the same way in Trebuchet.

I'm not committed to having a separate config launcher icon, and it may be removed.

**Comment by tetris4** [comment]
> Tuxpaint also has two launchers, and I bet it'd work the same way in Trebuchet.     

Yes I can replicate the same behavior with Tuxpaint. 

I just realized that when you kill all the running sessions, then the settings launch correctly.

> I'm not committed to having a separate config launcher icon, and it may be removed.

Yeah it is probably an overkill.

**Comment by quaap** [comment]
I've removed the config launcher in the next version.  The idea was that it was a look-in-settings-to-find-my-own-settings way to access the config while using launchtime, but it's confusing outside of that context, and people will find the settings via the up arrow at the bottom anyway.

**Comment by just-Nob** [comment]
*thumbs up*

I agree with you, the extra settings icon isn't necessary. :)
