### ISSUE TITLE
Better UI for app submission page

### ISSUE THREAD

**Issue by HenriDellal** [quaap/LaunchTime#66]
Hello.
I have some suggestions regarding the submission UI.
- A button to mark/unmark all items in the list;
- Change component info with app name;
- Localized category names in the list.

**Comment by quaap** [comment]
Before I talk about the bullet points, I'd like to discuss the purpose of the app submission page. The idea of the page is to tell me how people use LaunchTime and have categorized their apps, so I can better place apps in the future.  The reason the checkboxes are available is so that people can uncheck the few "sensitive" apps they may have and might not want other people to see (even though I don't know who they are).  

The data there is really for me, and the end user is not really meant to understand what it is, but I didn't want someone to not send me their app list because of a sensitive app in the data.

That said:

1) I'm implementing the select all/none buttons.

2) The data in the list is _exactly_ what gets sent to me.  I never see the app names, just the package/class names.  I think if I added the app name/label, people would think it gets sent to me as well, and it would make the page harder to figure out because each item would be larger.  That said, I can understand how it'd be harder for a non-English speaking (or at least a non-Latin-alphabet) user to figure out which app(s) in the list they don't want to send. Based on that, I'll see what I might be able to figure out. Might be a while though.

3) Same as 2.

Thanks for submitting feedback!
