### ISSUE TITLE
Option to choose if the tab is resized when selected

### ISSUE THREAD

**Issue by jiwopene** [quaap/LaunchTime#79]
The resizing of tabs on select (tap) is quite annoying with transparent tab background. Please add option to disable this or set the width change (0==disabled).

**Comment by quaap** [comment]
One way to accomplish this would be to edit the categories and change the full names to be the same as the short names.  That way, when selected or moved away from, the tabs shouldn't resize.

By the way, I'm making some changes in the next release: the category tabs will smoothly change size if needed, so the tabs lower on the list will smoothly slide up or down instead of instantly appearing in the new locations... assuming you have animations enabled (animation milliseconds > 0).

**Comment by quaap** [comment]
Caveat: even when the names are the same, the padding and font-size increase very slightly on the selected category, so the size will change a bit, but the movement should be tiny.
